# Generated by Django 4.2.7 on 2023-12-21 20:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pages', '0003_alter_page_autor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='autor',
        ),
        migrations.AddField(
            model_name='page',
            name='_autor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
