# Generated by Django 4.2.7 on 2023-12-22 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_page_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='imagen',
        ),
        migrations.AddField(
            model_name='page',
            name='imagen_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
