# Generated by Django 4.2.7 on 2023-12-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_remove_page_imagen_page_imagen_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='subtitulo',
            field=models.CharField(max_length=80),
        ),
    ]
