# Generated by Django 4.2.7 on 2023-12-24 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_alter_page_subtitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='cuerpo',
            field=models.TextField(max_length=20000),
        ),
    ]
